#6.3 Exercises 
user_age = input("enter your age then press enter")
print(user_age)
enter_key = input("hello user push any key and then press enter")
print(enter_key)
user_name = input("enter your name then press enter")
print(user_name)
var = (user_name)
favourite_movie = input("What is your favourite movie")
print(favourite_movie, "that is a good movie")
favourite_book = input("what is your favourite book")
print("i dont really like",favourite_book,"very much")
user_adjective = input("please type a adjective") 
print("you go for a ",user_adjective,"run")
user_verb = input("please type a verb")
print("you are going to go",user_verb,)
user_age2 = int(input("please type your age"))
print(f"you will be {user_age2 + 10}in ten years")
print(f"you were born in {2022 - user_age2}")
user_apples = int(input("please type how many apple you have"))
user_friends = int(input("please type how many friends you have"))
print(f"your friends can have {user_apples / user_friends} each")
user_pizza = int(input("how many pizza's would you like"))
user_people = int(input("how many frineds are you giving pizza to"))
print(f"your frineds can have this amount of slices {user_pizza * 8 / user_people}")
user_dollars = int(input("please type how many dollars you have stored"))
user_tv = int(input("please type in how much a tv is"))
print(f"you will have this {user_dollars - user_tv}")
print(F"if you wait you will have {user_dollars * 0.8}")
#current value of bitcoin 55,703
user_bitcoin = int(input("how many crypto currency do you have"))
bitcoin_value = 55703 
print(f"your portfolio is worth {user_bitcoin * bitcoin_value} dollars")
weekily_money = int(input("how much money do you earn a week"))
print(f"you will earn {weekily_money * 0.85}\n after tax ")
user_book =input("can i have a book name please")
book1 = user_book.lower()
book2 = user_book.upper()
book3 = user_book.title()
print(f"{book1}")
print(f"{book2}")
print(f"{book3}")
user_number45 = int(input("please give me a number"))
print(f"{user_book * user_number45}")
