#6.3 Exercises 
user_age = input("enter your age then press enter")
print(user_age)
enter_key = input("hello user push any key and then press enter")
print(enter_key)
user_name = input("enter your name then press enter")
print(user_name)
var = (user_name)
favourite_movie = input("What is your favourite movie")
print(favourite_movie, "that is a good movie")
favourite_book = input("what is your favourite book")
print("i dont really like",favourite_book,"very much")
user_adjective = input("please type a adjective") 
print("you go for a ",user_adjective,"run")
user_verb = input("please type a verb")
print("you are going to go",user_verb,)
user_age2 = input("please type your age")
float(,user_age2, + 10)