print("Arkyn")
print("Ms white")
print("kings high school")
#QUESTION 4
print("1200")
print("2047")
print("114")
print(658/7)
print("53")
print("apex legends")
print("english")
print(5/2)
print(5//2)
print("hello world" * 5)
print("\n")
print("curry and gaming with you friends now \n you live in the dark boy i cannot forget")
print("\n")
print("o i know what th \n ladies like")
print("a string is a sentence that is inside speech marks")
print("a float is a number with a decimal point")
print(543/3)
print(543//2)